server:
  port: 8081
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/jss
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true